# Generated by Django 5.2.17 on 2026-09-23 17:35

import django_mongodb_backend.fields
from django.db import migrations, models

import trips.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day_number", models.IntegerField()),
                ("date", models.CharField(max_length=10)),
                ("from_location", models.CharField(max_length=255)),
                ("to_location", models.CharField(max_length=255)),
                ("miles_driving_today", models.FloatField()),
                ("total_mileage_today", models.FloatField()),
                (
                    "log_meta",
                    django_mongodb_backend.fields.EmbeddedModelField(
                        embedded_model=trips.models.LogMeta
                    ),
                ),
                ("off_hrs", models.FloatField()),
                ("sb_hrs", models.FloatField()),
                ("d_hrs", models.FloatField()),
                ("on_hrs", models.FloatField()),
                (
                    "segments",
                    django_mongodb_backend.fields.EmbeddedModelArrayField(
                        embedded_model=trips.models.DutySegment
                    ),
                ),
                (
                    "remarks",
                    django_mongodb_backend.fields.EmbeddedModelArrayField(
                        embedded_model=trips.models.Remark
                    ),
                ),
                ("recap_on_duty_today", models.FloatField()),
                ("recap_a_last_7", models.FloatField()),
                ("recap_b_available", models.FloatField()),
                ("recap_c_last_5", models.FloatField()),
                ("restart_34_taken", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DutySegment",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("status", models.CharField(max_length=8)),
                ("start_min", models.IntegerField()),
                ("end_min", models.IntegerField()),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LogMeta",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("driver_name", models.CharField(blank=True, max_length=255)),
                ("co_driver_name", models.CharField(blank=True, max_length=255)),
                ("carrier_name", models.CharField(blank=True, max_length=255)),
                ("main_office_address", models.CharField(blank=True, max_length=255)),
                ("home_terminal_address", models.CharField(blank=True, max_length=255)),
                ("truck_tractor_no", models.CharField(blank=True, max_length=255)),
                ("trailer_no", models.CharField(blank=True, max_length=255)),
                ("shipping_doc_no", models.CharField(blank=True, max_length=255)),
                ("shipper_commodity", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Remark",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("at_min", models.IntegerField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StopRecord",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("seq", models.IntegerField()),
                ("type", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=255)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("mile_marker", models.FloatField()),
                ("arrive_at", models.DateTimeField()),
                ("depart_at", models.DateTimeField()),
                ("status", models.CharField(max_length=8)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current",
                    django_mongodb_backend.fields.EmbeddedModelField(
                        embedded_model=trips.models.Location
                    ),
                ),
                (
                    "pickup",
                    django_mongodb_backend.fields.EmbeddedModelField(
                        embedded_model=trips.models.Location
                    ),
                ),
                (
                    "dropoff",
                    django_mongodb_backend.fields.EmbeddedModelField(
                        embedded_model=trips.models.Location
                    ),
                ),
                ("cycle_used_hrs", models.FloatField()),
                ("start_at", models.DateTimeField()),
                ("home_timezone", models.CharField(max_length=64)),
                ("include_inspections", models.BooleanField()),
                (
                    "log_meta",
                    django_mongodb_backend.fields.EmbeddedModelField(
                        embedded_model=trips.models.LogMeta
                    ),
                ),
                ("total_miles", models.FloatField()),
                ("total_driving_hrs", models.FloatField()),
                ("total_on_duty_hrs", models.FloatField()),
                ("arrive_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("log_days", models.IntegerField()),
                ("cycle_used_end_hrs", models.FloatField()),
                ("route_geometry", models.JSONField()),
                ("route_legs", models.JSONField()),
                (
                    "stops",
                    django_mongodb_backend.fields.EmbeddedModelArrayField(
                        embedded_model=trips.models.StopRecord
                    ),
                ),
                (
                    "daily_logs",
                    django_mongodb_backend.fields.EmbeddedModelArrayField(
                        embedded_model=trips.models.DailyLog
                    ),
                ),
            ],
            options={
                "db_table": "trips",
            },
        ),
    ]
