# Generated by Django 5.2.17 on 2026-09-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stoprecord",
            name="reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
